# all-temp-fork-pvt-scheduled_sync_with_upstream-weekly.yaml
# ToDo
# This work flow does not work for private repositories yet and has to be be further pursued.  I just gave up for the moment ;-).
name: Template Scheduled Merge Private Fork with Upstream - Weekly

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly on Sunday at midnight UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  all-temp-fork-pvt-scheduled_sync_with_upstream-weekly:
    permissions:
      id-token: write
      contents: write
    uses: BrightEdgeeServices/devops-automation/.github/workflows/all-wf-fork-pvt-scheduled_sync_with_upstream-def.yaml@master
    secrets:
      GH_REPO_ACCESS_BEE_MASTER: ${{secrets.GH_REPO_ACCESS_BEE_MASTER }}
      GH_REPO_ACCESS_RTE_MASTER: ${{secrets.GH_REPO_ACCESS_RTE_MASTER }}
      # MYSQL_PASSWORD:            ${{secrets.MYSQL_PASSWORD}}
      # MYSQL_ROOT_PASSWORD:       ${{secrets.MYSQL_ROOT_PASSWORD}}
      # MYSQL_USER:                ${{secrets.MYSQL_USER}}
      # PYPI_API_TOKEN_PROD:       ${{secrets.PYPI_API_TOKEN_PROD}}
      ORIGINAL_OWNER:       ${{vars.ORIGINAL_OWNER}}
      ORIGINAL_REPO_NAME:   ${{vars.ORIGINAL_REPO_NAME}}
      # RELEASE_EMAIL_USER:        ${{secrets.RELEASE_EMAIL_USER }}
      # RELEASE_EMAIL_PASSWORD:    ${{secrets.RELEASE_EMAIL_PASSWORD }}
