# all-temp-fork-pvt-scheduled_sync_with_upstream-daily.yaml
# ToDo
# This work flow does not work for private repositories yet and has to be be further pursued.  I just gave up for the moment ;-).
name: Template Scheduled Merge Private Fork with Upstream - Daily

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  all-temp-fork-pvt-scheduled_sync_with_upstream-daily:
    permissions:
      id-token: write
      contents: write
    #    if: github.event.pull_request.merged == true
    uses: BrightEdgeeServices/devops-automation/.github/workflows/all-wf-fork-pvt-scheduled_sync_with_upstream-def.yaml@master
    #    with:
    #  run_deploy: ${{ startsWith(github.ref, 'refs/tags/') == true }}
    #      original_owner:     ${{ vars.ORIGINAL_OWNER }}
    #      original_repo_name: ${{ vars.ORIGINAL_REPO_NAME }}
    # secrets: inherit
    secrets:
      GH_REPO_ACCESS_BEE_MASTER: ${{secrets.GH_REPO_ACCESS_BEE_MASTER }}
      GH_REPO_ACCESS_RTE_MASTER: ${{secrets.GH_REPO_ACCESS_RTE_MASTER }}
      # MYSQL_PASSWORD:            ${{secrets.MYSQL_PASSWORD}}
      # MYSQL_ROOT_PASSWORD:       ${{secrets.MYSQL_ROOT_PASSWORD}}
      # MYSQL_USER:                ${{secrets.MYSQL_USER}}
      # PYPI_API_TOKEN_PROD:       ${{secrets.PYPI_API_TOKEN_PROD}}
      ORIGINAL_OWNER:       ${{vars.ORIGINAL_OWNER}}
      ORIGINAL_REPO_NAME:   ${{vars.ORIGINAL_REPO_NAME}}
      # RELEASE_EMAIL_USER:        ${{secrets.RELEASE_EMAIL_USER }}
      # RELEASE_EMAIL_PASSWORD:    ${{secrets.RELEASE_EMAIL_PASSWORD }}
