# py-temp-pub-pvt_no_docker-def.yaml
# This is a template and should not be changed unless you are familiar with the
# reusable GitHub Actions strategy of the company.
name: Python Template Publish Private No-Docker

on:
  push:
    branches-ignore:
      - master
      - main

jobs:
  py-temp-dep-pvt_no_docker-def:
    permissions:
      id-token: write
      contents: write
      pull-requests: write

    uses: BrightEdgeeServices/devops-automation/.github/workflows/py-wf-pub-pvt_no_docker-def.yaml@master
    with:
      run_publish: true
    # secrets: inherit
    secrets:
      GH_REPO_ACCESS_BEE_MASTER: ${{secrets.GH_REPO_ACCESS_BEE_MASTER }}
      GH_REPO_ACCESS_RTE_MASTER: ${{secrets.GH_REPO_ACCESS_RTE_MASTER }}
#      MYSQL_PASSWORD:            ${{secrets.MYSQL_PASSWORD}}
#      MYSQL_ROOT_PASSWORD:       ${{secrets.MYSQL_ROOT_PASSWORD}}
#      MYSQL_USER:                ${{secrets.MYSQL_USER}}
#      RELEASE_EMAIL_USER:        ${{secrets.RELEASE_EMAIL_USER }}
#      RELEASE_EMAIL_PASSWORD:    ${{secrets.RELEASE_EMAIL_PASSWORD }}
