# GitHub Actions Script: python-template-pypi.yaml
# This is a template and should not be changed unless you are familiar with the
# reusable GitHub Actions strategy of the company.
name: Python Default Template

on:
  push:

jobs:
  default-deployment-pipeline:
    permissions:
      id-token: write
      contents: write
    #    if: github.event.pull_request.merged == true
    uses: RealTimeEvents/devops-automation/.github/workflows/python-wf-default-pypi-pipeline.yaml@master
    with:
      run_deploy: startsWith(github.ref, 'refs/tags/') == true
    secrets: inherit
