# python-template-deploy-private-with-docker.yaml
# This is a template and should not be changed unless you are familiar with the
# reusable GitHub Actions strategy of the company.
name: Python Template Deploy Private With-Docker

on:
  push:

jobs:
  python-template-deploy-private-with-docker:
    permissions:
      id-token: write
      contents: write
    #    if: github.event.pull_request.merged == true
    uses: RealTimeEvents/devops-automation/.github/workflows/python-wf-deploy-private-with-docker.yaml@master
    with:
      run_deploy: ${{ startsWith(github.ref, 'refs/tags/') == true }}
    # secrets: inherit
    secrets:
      RELEASE_EMAIL_USER: ${{ secrets.RELEASE_EMAIL_USER }}
      RELEASE_EMAIL_PASSWORD: ${{ secrets.RELEASE_EMAIL_PASSWORD }}
