# react-temp-pvt-publish-release_notify_after_merge-def.yaml
# This template triggers a reusable workflow that creates a release and sends a notice
# after a Pull Request is merged into master. The release tag is derived from
# package.json's version, prefixed with 'v'.
name: Release After Merge

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  Release-After-Merge:
    if: ${{ github.event.pull_request.merged == true }}
    permissions:
      contents: write
    uses: BrightEdgeeServices/devops-automation/.github/workflows/react-wf-publish-pvt-release_notify_after_merge-def.yaml@master
    secrets:
      GH_REPO_ACCESS_BEE_MASTER: ${{secrets.GH_REPO_ACCESS_BEE_MASTER }}
      GH_REPO_ACCESS_RTE_MASTER: ${{secrets.GH_REPO_ACCESS_RTE_MASTER }}
      RELEASE_EMAIL_USER:     ${{vars.RELEASE_EMAIL_USER }}
      RELEASE_EMAIL_PASSWORD: ${{secrets.RELEASE_EMAIL_PASSWORD }}
