# py-pc-pr-def.yaml
name: PR-and-Build

on:
  workflow_call:
    secrets:
      GH_REPO_ACCESS_BEE_MASTER:
        required: true
      GH_REPO_ACCESS_RTE_MASTER:
        required: true

jobs:
  Create-PR:
#    if: ${{ github.ref_type != 'tag' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    strategy:
      fail-fast: true
      matrix:
        python-version: [ '3.12' ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Git identity
        run:  |
              git config --global user.name 'GitHub Action'
              git config --global user.email 'action@github.com'

      - name: Create pull request into master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH="${GITHUB_REF_NAME}"
          BASE="master"
          TITLE="Publish: Merge ${BRANCH} into ${BASE}"
          BODY="Automated PR generated by reusable workflow."

          echo "Attempting to create PR from '${BRANCH}' to '${BASE}'"
          # If a PR already exists for this head->base pair, skip creating a new one
          COUNT=$(gh pr list --head "$BRANCH" --base "$BASE" --state open --json number --jq 'length')
          if [ "$COUNT" -gt 0 ]; then
            echo "A pull request from '$BRANCH' to '$BASE' already exists. Skipping creation."
          else
            # Create PR only if none exists
            gh pr create \
              --base "$BASE" \
              --head "$BRANCH" \
              --title "$TITLE" \
              --body "$BODY"
          fi
