# py-pc-dep-no_docker-def.yaml
# ToDo
# This is a copied version and has to be fixed
name: Build-and-Deploy

on:
  workflow_call:
    #    inputs:
    #      original_owner:
    #        description: "Set to original owner of the fork."
    #        required:    true
    #        default:     ""
    #        type:        string
    #      original_repo_name:
    #        description: "Set to original repo name of the fork."
    #        required:    true
    #        default:     ""
    #        type:        string
    secrets:
      GH_REPO_ACCESS_BEE_MASTER:
        required: true
      GH_REPO_ACCESS_RTE_MASTER:
        required: true
#      RELEASE_EMAIL_USER:
#        required: true
#      RELEASE_EMAIL_PASSWORD:
#        required: true

jobs:
  Merge:
    runs-on: ${{ matrix.os }}
    env:
      ORIGINAL_OWNER:     ${{vars.ORIGINAL_OWNER}}
      ORIGINAL_REPO_NAME: ${{vars.ORIGINAL_REPO_NAME}}

    strategy:
      fail-fast: true
      matrix:
        os: [ 'ubuntu-latest' ]
        python-version: [ '3.12' ]

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Git identity
        run:  |
              git config --global user.name 'GitHub Action'
              git config --global user.email 'action@github.com'

      #      - name:              Merge into master
      #        id:                merge
      #        run:               |
      #                           git checkout master
      #                           git merge --no-ff $GITHUB_REF
      #        continue-on-error: false
      #
      #      - name: Push to master
      #        if:   steps.merge.outcome == 'success'
      #        run:  |
      #              git push origin master
      #        env:
      #          GH_TOKEN: ${{ secrets.GH_REPO_ACCESS_CURR_USER }}

      - name: Fetch upstream and merge
        run:  |
              git remote add upstream https://github.com/$ORIGINAL_OWNER/$ORIGINAL_REPO_NAME.git
              git fetch upstream
              git checkout master
              git merge --no-edit upstream/master

      - name: Push changes
        run:  git push origin master

  #      - name: Debug Environment
  #        run: env
