# py-pc-pub-no_docker-def.yaml
name: Build-and-PR

on:
  workflow_call:
    secrets:
      GH_REPO_ACCESS_BEE_MASTER:
        required: true
      GH_REPO_ACCESS_RTE_MASTER:
        required: true

jobs:
  Create-PR:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
#      id-token: write

    strategy:
      fail-fast: true
      matrix:
        python-version: [ '3.12' ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Git identity
        run:  |
              git config --global user.name 'GitHub Action'
              git config --global user.email 'action@github.com'

      - name: Create pull request into master
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          # head defaults to the current ref branch; can be overridden via `head: <branch>` if needed
          title: "Publish: Merge ${{ github.ref_name }} into master"
          body: |
            Automated PR generated by reusable workflow.

  Build-Only:
    runs-on: ubuntu-latest
    needs: Create-PR

    permissions:
      contents: write
      id-token: write

    strategy:
      fail-fast: true
      matrix:
        python-version: [ "3.13" ]

    env:
      GH_REPO_ACCESS_BEE_MASTER: ${{secrets.GH_REPO_ACCESS_BEE_MASTER}}
      GH_REPO_ACCESS_RTE_MASTER: ${{secrets.GH_REPO_ACCESS_RTE_MASTER}}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to include tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture:   x64

      - name: Install Poetry
        run:  |
              curl -sSL https://install.python-poetry.org | python3 -
              echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Configure Poetry
        run:  |
              poetry config keyring.enabled false
              poetry config http-basic.BEE __token__ ${{ secrets.GH_REPO_ACCESS_BEE_MASTER }}
              poetry config http-basic.RTE __token__ ${{ secrets.GH_REPO_ACCESS_RTE_MASTER }}

      - name: Install dependencies
        run:  |
              poetry install --with dev

      # ToDo
      # Deploy to production must be inserted here
      - name: Build and publish with Poetry
        run:  |
              poetry build
