# py-wf-pr-pvt_no_docker-def.yaml
name: Pre-Commit, CI and PR (default)

on:
  workflow_call:
#    inputs:
#      run_publish:
#        description: "Set to 'true' to run the Build-and-Publish job tag was specified."
#        required:    true
#        default:     false
#        type:        boolean
    secrets:
      GH_REPO_ACCESS_BEE_MASTER:
        required: true
      GH_REPO_ACCESS_RTE_MASTER:
        required: true
#      MYSQL_PASSWORD:
#        required: true
#      MYSQL_ROOT_PASSWORD:
#        required: true
#      MYSQL_USER:
#        required: true
#      RELEASE_EMAIL_USER:
#        required: true
#      RELEASE_EMAIL_PASSWORD:
#        required: true

jobs:
  Pre-Commit:
    uses:    BrightEdgeeServices/devops-automation/.github/workflows/py-pc-precom-def.yaml@master
    secrets: inherit

  CI:
    uses: BrightEdgeeServices/devops-automation/.github/workflows/py-pc-ci-pvt_no_docker-def.yaml@master
    secrets:
      GH_REPO_ACCESS_BEE_MASTER: ${{secrets.GH_REPO_ACCESS_BEE_MASTER }}
      GH_REPO_ACCESS_RTE_MASTER: ${{secrets.GH_REPO_ACCESS_RTE_MASTER }}

  PR:
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    # Only run when the current ref is a tag named 'pr'
    if:   ${{ github.ref_type == 'tag' && github.ref_name == 'pr' }}
    needs:
      - Pre-Commit
      - CI
    uses: BrightEdgeeServices/devops-automation/.github/workflows/py-pc-pr-def.yaml@master
    secrets:
      GH_REPO_ACCESS_BEE_MASTER: ${{secrets.GH_REPO_ACCESS_BEE_MASTER }}
      GH_REPO_ACCESS_RTE_MASTER: ${{secrets.GH_REPO_ACCESS_RTE_MASTER }}

  Cleanup-Delete-pr-Tag:
    permissions:
      contents: write
    if: ${{ always() && github.ref_type == 'tag' && github.ref_name == 'pr' }}
    needs:
      - Pre-Commit
      - CI
      - PR
    uses: BrightEdgeeServices/devops-automation/.github/workflows/py-pc-pr-cleanup_tag-def.yaml@master
    secrets:
      GH_REPO_ACCESS_BEE_MASTER: ${{secrets.GH_REPO_ACCESS_BEE_MASTER }}
      GH_REPO_ACCESS_RTE_MASTER: ${{secrets.GH_REPO_ACCESS_RTE_MASTER }}
