# py-wf-pub-after_merge-def.yaml
name: Publish After PR Merge (Wrapper)

on:
  workflow_call:
    inputs:
      tag_name:
        description: "Optional explicit tag name. If omitted, workflow derives v{version} from pyproject.toml"
        required: false
        type: string
    secrets:
      RELEASE_EMAIL_USER:
        required: true
      RELEASE_EMAIL_PASSWORD:
        required: true

jobs:
  Release-and-Notify:
    uses: BrightEdgeeServices/devops-automation/.github/workflows/py-pc-rel-build_notify-def.yaml@master
    with:
      tag_name: ${{ inputs.tag_name }}
    secrets:
      RELEASE_EMAIL_USER:     ${{ secrets.RELEASE_EMAIL_USER }}
      RELEASE_EMAIL_PASSWORD: ${{ secrets.RELEASE_EMAIL_PASSWORD }}
