# py-wf-dep-pvt_with_docker-def.yaml
name: Default Deployment Pipeline

on:
  workflow_call:
    inputs:
      run_deploy:
        description: "Set to 'true' to run the Build-and-Deploy job if a tag was specified."
        required:    true
        default:     false
        type:        boolean
    secrets:
      GH_REPO_ACCESS_BEE_MASTER:
        required: true
      GH_REPO_ACCESS_RTE_MASTER:
        required: true
      INSTALLER_USER_ID:
        required: true
      INSTALLER_USER_PWD:
        required: true
      MYSQL_DATABASE:
        required: true
      MYSQL_HOST:
        required: true
      MYSQL_PASSWORD:
        required: true
      MYSQL_ROOT_PASSWORD:
        required: true
      MYSQL_USER:
        required: true
      RELEASE_EMAIL_USER:
        required: true
      RELEASE_EMAIL_PASSWORD:
        required: true

jobs:
  Pre-Commit:
    uses:    BrightEdgeeServices/devops-automation/.github/workflows/py-pc-precom-def.yaml@master
    secrets: inherit

  CI:
    uses: BrightEdgeeServices/devops-automation/.github/workflows/py-pc-ci-pvt_with_docker-def.yaml@master
    secrets:
      GH_REPO_ACCESS_BEE_MASTER: ${{secrets.GH_REPO_ACCESS_BEE_MASTER }}
      GH_REPO_ACCESS_RTE_MASTER: ${{secrets.GH_REPO_ACCESS_RTE_MASTER }}
      INSTALLER_USER_ID: ${{secrets.INSTALLER_USER_ID }}
      INSTALLER_USER_PWD: ${{secrets.INSTALLER_USER_PWD }}
      MYSQL_DATABASE: ${{secrets.MYSQL_DATABASE }}
      MYSQL_HOST: ${{secrets.MYSQL_HOST }}
      MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD }}
      MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_TCP_PORT: ${{secrets.MYSQL_TCP_PORT }}
      MYSQL_USER: ${{secrets.MYSQL_USER }}
      PROJECT_NAME: ${{secrets.PROJECT_NAME }}

  Build-and-Deploy:
    permissions:
      id-token: write
      contents: write
    if:   ${{ inputs.run_deploy == true }}
    needs:
      - Pre-Commit
      - CI
    uses: BrightEdgeeServices/devops-automation/.github/workflows/py-pc-dep-with_docker-def.yaml@master
    secrets:
      GH_REPO_ACCESS_BEE_MASTER: ${{secrets.GH_REPO_ACCESS_BEE_MASTER }}
      GH_REPO_ACCESS_RTE_MASTER: ${{secrets.GH_REPO_ACCESS_RTE_MASTER }}
      RELEASE_EMAIL_PASSWORD:    ${{secrets.RELEASE_EMAIL_PASSWORD }}
      RELEASE_EMAIL_USER:        ${{secrets.RELEASE_EMAIL_USER }}
