# py-wf-dep-pvt_with_docker-def.yaml
# ToDo
# This is a copied version and has to be fixed
name: Default Deployment Pipeline

on:
  workflow_call:
    inputs:
      run_deploy:
        description: "Set to 'true' to run the Build-and-Deploy job if a tag was specified."
        required:    true
        default:     false
        type:        boolean
    secrets:
      GH_REPO_ACCESS_BEE_MASTER:
        required: true
      GH_REPO_ACCESS_RTE_MASTER:
        required: true
      MYSQL_PASSWORD:
        required: true
      MYSQL_USER:
        required: true
      RELEASE_EMAIL_USER:
        required: true
      RELEASE_EMAIL_PASSWORD:
        required: true

jobs:
  Pre-Commit:
    uses:    RealTimeEvents/devops-automation/.github/workflows/py-pc-precom-def.yaml@master
    secrets: inherit

  CI:
    uses:    RealTimeEvents/devops-automation/.github/workflows/py-pc-ci-pvt_with_docker-def.yaml@master
    secrets: inherit

  Build-and-Deploy:
    permissions:
      id-token: write
      contents: write
    if:      ${{ inputs.run_deploy == true }}
    needs:
      - Pre-Commit
      - CI
    uses:    RealTimeEvents/devops-automation/.github/workflows/py-pc-dep-with_docker-def.yaml@master
    secrets: inherit
