# python-process-pypi-no-docker.yaml
# ToDo
# This is a copied version and has to be fixed
name: Build-and-Publish-to-PyPI

on:
  workflow_call:

jobs:
  Build-and-Publish-to-PyPI:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write
      id-token: write

    strategy:
      fail-fast: true
      matrix:
        os: [ 'ubuntu-latest' ]
        python-version: [ '3.13' ]

    env:
      TAG: ""

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to include tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Configure Poetry
        run: |
          poetry config keyring.enabled false
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN_PROD }}
          # poetry config http-basic.PoetryPrivate __token__ ${{ secrets.GH_REPO_ACCESS_CURR_USER }}
          # poetry source add --priority=explicit PoetryPrivate https://github.com/BrightEdgeeServices/PoetryPrivate.git
          # poetry add git+https://github.com/BrightEdgeeServices/PoetryPrivate.git

      - name: Install dependencies
        run: |
          poetry install --with dev

      - name: Build and publish with Poetry
        run: |
          poetry build
          poetry publish

      #      - name: Dump environment variables
      #        run: |
      #          env
      #          echo "${{ toJson(github) }}"

      # TODO: The reference in the Release notes must be corrected.
      - name: New release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.head_ref }}
          name: ${{ github.head_ref }}
          body_path: ${{ github.workspace }}/ReleaseNotes.md
          draft: false
          prerelease: false

  Send-Notice:
    needs: Build-and-Publish-to-PyPI
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ 'ubuntu-latest' ]
        python-version: [ '3.13' ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Configuration details needed:
      # Sender details: userid, password, server_address and server_port
      - name: Send release email notification
        uses: betterfor/action-send-mail@main
        with:
          server_address: mail.realtimeevents.co
          server_port: 465
          username: ${{ secrets.RELEASE_EMAIL_USER }}
          password: ${{ secrets.RELEASE_EMAIL_PASSWORD }}
          subject: 'New Release: ${{ github.repository }} ${{ github.ref_name }}'
          to: development@citiqprepaid.co.za
          from: Development Messenger
          html_body: |
            <table style="font-family: verdana;font-size:90%; border-collapse:collapse; border-style: double; border-color: 000000; border-width: 3px">
            <colgroup>
              <col style="text-align:right">
              <col style="text-align:left">
            </colgroup>
            <tr>
              <th style="text-align: center; border-bottom-style: double; border-right-style: double; border-right-width: 1px; border-bottom-width: 3px">Description</th>
              <th style="text-align: center; border-bottom-style: double; border-left-style: double; border-bottom-width: 3px; border-left-width: 1px">Detail</th>
            </tr>
            <tr>
              <td style="text-align: right; border-right-style: solid; border-bottom-style: dotted; border-right-width: 1px;border-bottom-width: 1px">Repository:</td>
              <td style="text-align: left; border-bottom-style: dotted; border-left-style: solid; border-left-width: 1px;border-bottom-width: 1px">${{ github.repository }}</td>
            </tr>
            <tr>
              <td style="text-align: right; border-right-style: solid; border-bottom-style: dotted; border-right-width: 1px;border-bottom-width: 1px">Release:</td>
              <td style="text-align: left; border-bottom-style: dotted; border-left-style: solid; border-left-width: 1px;border-bottom-width: 1px">${{ github.ref_name }}</td>
            </tr>
            <tr>
              <td style="text-align: right; border-right-style: solid; border-bottom-style: dotted; border-right-width: 1px;border-bottom-width: 1px">Actor:</td>
              <td style="text-align: left; border-bottom-style: dotted; border-left-style: solid; border-left-width: 1px;border-bottom-width: 1px">${{ github.actor }}</td>
            </tr>
            <tr>
              <td style="text-align: right; border-right-style: solid; border-bottom-style: dotted; border-right-width: 1px;border-bottom-width: 1px">Workflow:</td>
              <td style="text-align: left; border-bottom-style: dotted; border-left-style: solid; border-left-width: 1px;border-bottom-width: 1px">${{ github.workflow }}</td>
            </tr>
            <tr>
              <td style="text-align: right; border-right-style: solid; border-right-width: 1px">Release URL:</td>
              <td style="text-align: left; border-left-style: solid; border-left-width: 1px"><a href="https://github.com/${{ github.repository }}/releases/tag/${{github.ref_name}}">Click here</a></td>
            </tr>
            </table><br>'
          # cc: a@example.com,b@example.com
          # bcc: c@example.com,d@example.com
          # Optional recipient of the email response
          # reply_to: luke@example.com
          # Optional Message ID this message is replying to
          # in_reply_to: <random-luke@example.com>
          # Optional converting Markdown to HTML (set content_type to text/html too)
          # convert_markdown: true
          # Optional attachments
          # attachments: README.md
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: normal
