# python-wf-default-deploy-pipeline.yaml
name: Default Deployment Pipeline

on:
  workflow_call:
    inputs:
      run_deploy:
        description: "Set to 'true' to run the Build-and-Deploy job. For PR merges into main, pass 'true'. For merges into develop, pass 'false'."
        required: true
        default: false
        type: boolean

jobs:
  Pre-Commit:
    uses: RealTimeEvents/devops-automation/.github/workflows/python-process-precommit-default.yaml@master
    secrets: inherit

  CI:
    uses: RealTimeEvents/devops-automation/.github/workflows/python-process-ci-default.yaml@master
    secrets: inherit

  Build-and-Deploy:
    permissions:
      id-token: write
      contents: write
    if: ${{ inputs.run_deploy == true }}
    needs:
      - Pre-Commit
      - CI
    uses: RealTimeEvents/devops-automation/.github/workflows/python-process-deploy-default.yaml@master
    secrets: inherit

