# python-wf-pypi-public-no-docker.yaml
# ToDo
# This is a copied version and has to be fixed
name: Default PyPI Pipeline

on:
  workflow_call:
    inputs:
      run_deploy:
        description: "Set to 'true' to run the Build-and-Publish-to-PyPI job if a tag was specified."
        required: true
        default: false
        type: boolean
    secrets:
      PYPI_API_TOKEN_PROD:
        required: true
      RELEASE_EMAIL_USER:
        required: true
      RELEASE_EMAIL_PASSWORD:
        required: true

jobs:
  Pre-Commit:
    uses: RealTimeEvents/devops-automation/.github/workflows/python-process-precommit-default.yaml@master
    secrets: inherit

  CI:
    uses: RealTimeEvents/devops-automation/.github/workflows/python-process-ci-public-no-docker.yaml@master
    secrets: inherit

  Build-and-Publish-to-PyPI:
    permissions:
      id-token: write
      contents: write
    if: ${{ inputs.run_deploy == true }}
    needs:
      - Pre-Commit
      - CI
    uses: RealTimeEvents/devops-automation/.github/workflows/python-process-pypi.yaml@master
    secrets: inherit

