# python-wf-pypi-public-with-docker.yaml
name: Default PyPI Pipeline

on:
  workflow_call:
    inputs:
      run_deploy:
        description: "Set to 'true' to run the Build-and-Publish-to-PyPI job if a tag was specified."
        required: true
        default: false
        type: boolean
    secrets:
      PYPI_API_TOKEN_PROD:
        required: true

jobs:
  check-pypi-token:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ 'ubuntu-latest' ]
        python-version: [ '3.12' ]

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Check if PYPI_API_TOKEN_PROD is set
        run: |
          if [ -z "${{ secrets.PYPI_API_TOKEN_PROD }}" ]; then
            echo "PYPI_API_TOKEN_PROD is empty!"
            exit 1
          else
            echo "PYPI_API_TOKEN_PROD is set."
          fi

  Pre-Commit:
    uses: RealTimeEvents/devops-automation/.github/workflows/python-process-precommit-default.yaml@master
    secrets: inherit

  CI:
    uses: RealTimeEvents/devops-automation/.github/workflows/python-process-ci-public-with-docker.yaml@master
    secrets: inherit

  Build-and-Publish-to-PyPI:
    permissions:
      id-token: write
      contents: write
    if: ${{ inputs.run_deploy == true }}
    needs:
      - check-pypi-token
      - Pre-Commit
      - CI
    uses: RealTimeEvents/devops-automation/.github/workflows/python-process-pypi-with-docker.yaml@master
    secrets: inherit

